[build]
publish = "public"

[context.production]
command = "ln -s repo ../endg.github.io && hugo  --baseURL=${URL}"

[context.branch-deploy]
command = "ln -s repo ../endg.github.io && hugo --baseURL=${DEPLOY_PRIME_URL}"

[context.deploy-preview]
command = "ln -s repo ../endg.github.io && hugo  --baseURL=${DEPLOY_PRIME_URL}"

[build.environment]
HUGO_VERSION = "0.48"
